# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
# - master
variables:
  - name: ADDON
    value: rsyslog
pr:
  branches:
    include:
    - '*' 
pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    docker run --rm --privileged -v ~/.docker:/root/.docker -v /var/run/docker.sock:/var/run/docker.sock:ro -v ${PWD}/$ADDON:/data homeassistant/amd64-builder --all --test -t /data
  displayName: 'Test Add-on'
