name: Rsyslog
version: '2022.1.0'
slug: rsyslog
url: https://addons.mathesonsteplock.ca/docs/addons/rsyslog/basic-config
description: Rsyslog Home Assistant Add-on for monitoring the logs of your Tasmota
  devices
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
image: ikifar/rsyslog-ha-{arch}
boot: auto
map:
  - share:rw
ports:
  514/tcp: 514
  514/udp: 514
ports_description:
  514/tcp: rsyslog TCP Port
  514/udp: rsyslog UDP Port
options: {}
schema: {}